task:
  ['yolov5x.pt', 'yolov5x.pt', 'yolov5x.pt', 'yolov5x.pt', 'yolov5x.pt', 'yolov5x.pt',
  'yolov5x.pt', 'yolov5x.pt', 'yolov5x.pt', 'yolov5x.pt']

deadline:
  [300, 300, 300, 300, 300, 300, 300, 300, 300, 300]

streams: 1 # Indicate the number of video streams

